# SPDX-FileCopyrightText: 2025 VerifyEncoding contributors <https://github.com/ForNeVeR/VerifyEncoding>
#
# SPDX-License-Identifier: MIT

name: main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        image:
          - macos-14
          - ubuntu-24.04
          - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.image }}
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -RequiredVersion 5.7.1 -Force
      - name: Run tests
        shell: pwsh
        run: Import-Module Pester -PassThru && Invoke-Pester -Output Detailed ./Test-Encoding.Test.ps1
      - name: Check the module manifest
        shell: pwsh
        run: Test-ModuleManifest VerifyEncoding/VerifyEncoding.psd1

  licenses:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the repository
      uses: actions/checkout@v5
    - name: REUSE license check
      uses: fsfe/reuse-action@v5

  encoding:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the repository
      uses: actions/checkout@v5

    - name: Verify encoding
      shell: pwsh
      run: Import-Module ./VerifyEncoding/VerifyEncoding.psd1 && Test-Encoding
