# SPDX-FileCopyrightText: 2024-2025 VerifyEncoding contributors <https://github.com/ForNeVeR/VerifyEncoding>
#
# SPDX-License-Identifier: MIT
name: Release
on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - id: version
        name: Get version
        shell: pwsh
        run: echo "version=$(scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT
      - name: Read changelog
        uses: ForNeVeR/ChangelogAutomation.action@v2
        with:
          output: ./release-notes.md
      - name: Read text changelog
        uses: ForNeVeR/ChangelogAutomation.action@v2
        with:
          format: PlainText
          output: ./release-notes.txt
      - name: Set up the module properties
        shell: pwsh
        run: Update-ModuleManifest VerifyEncoding/VerifyEncoding.psd1 -ReleaseNotes $(Get-Content -LiteralPath release-notes.txt -Raw)

      - name: Pack the module for upload
        shell: pwsh
        run: Compress-Archive VerifyEncoding/* VerifyEncoding-${{ steps.version.outputs.version }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |-
            ./release-notes.md
            ./VerifyEncoding/Test-Encoding.ps1
            ./VerifyEncoding-${{ steps.version.outputs.version }}.zip

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Upload the module to the PowerShell Gallery
        shell: pwsh
        run: Publish-Module -Path VerifyEncoding -Repository PSGallery -NuGetApiKey $env:POWERSHELL_GALLERY_KEY -Verbose
        env:
          POWERSHELL_GALLERY_KEY: ${{ secrets.POWERSHELL_GALLERY_KEY }}

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./release-notes.md
          name: VerifyEncoding v${{ steps.version.outputs.version }}
          files: |-
            ./VerifyEncoding/Test-Encoding.ps1
            ./VerifyEncoding-${{ steps.version.outputs.version }}.zip
